Repository martinoywa/numbers-tutor, pull requests merged in 2020-12, with the labels that each got.

#22 Retrieve canvas image data.
  assets/js/app.js
Labels: Feature, enhancement

#21 Build the User Interface.
  .vscode/settings.json
  assets/css/style.css
  assets/css/style.css.map
  assets/img/background.svg
  assets/js/app.js
  assets/scss/style.scss
  html/voice.html
  html/write.html
  index.html
Labels: Feature

#27 Speech to text numbers to words
  app/ai/speak/audio_to_text.py
  app/ai/speak/tests/test_speak.py
Labels: enhancement
